# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 563)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("gui_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("gui_icon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("gui_icon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("gui_icon.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("gui_icon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("gui_icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("gui_icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pair_group1 = QtWidgets.QGroupBox(self.centralwidget)
        self.pair_group1.setObjectName("pair_group1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pair_group1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pair1 = QtWidgets.QWidget(self.pair_group1)
        self.pair1.setObjectName("pair1")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.pair1)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.verticalLayout_62 = QtWidgets.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.label_89 = QtWidgets.QLabel(self.pair1)
        self.label_89.setObjectName("label_89")
        self.horizontalLayout_75.addWidget(self.label_89)
        self.pair_name1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pair_name1.setFont(font)
        self.pair_name1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pair_name1.setObjectName("pair_name1")
        self.horizontalLayout_75.addWidget(self.pair_name1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.pair1)
        self.label.setObjectName("label")
        self.horizontalLayout_75.addWidget(self.label)
        self.update_time1 = QtWidgets.QLabel(self.pair1)
        self.update_time1.setObjectName("update_time1")
        self.horizontalLayout_75.addWidget(self.update_time1)
        self.allert_symbol1 = QtWidgets.QLabel(self.pair1)
        self.allert_symbol1.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.allert_symbol1.setFont(font)
        self.allert_symbol1.setObjectName("allert_symbol1")
        self.horizontalLayout_75.addWidget(self.allert_symbol1)
        self.verticalLayout_63.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.label_90 = QtWidgets.QLabel(self.pair1)
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_77.addWidget(self.label_90)
        self.price1 = QtWidgets.QLabel(self.pair1)
        self.price1.setObjectName("price1")
        self.horizontalLayout_77.addWidget(self.price1)
        self.price_converted1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.price_converted1.setFont(font)
        self.price_converted1.setObjectName("price_converted1")
        self.horizontalLayout_77.addWidget(self.price_converted1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem1)
        self.verticalLayout_64.addLayout(self.horizontalLayout_77)
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.label_92 = QtWidgets.QLabel(self.pair1)
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_78.addWidget(self.label_92)
        self.volume1 = QtWidgets.QLabel(self.pair1)
        self.volume1.setObjectName("volume1")
        self.horizontalLayout_78.addWidget(self.volume1)
        self.volume_converted1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_converted1.setFont(font)
        self.volume_converted1.setObjectName("volume_converted1")
        self.horizontalLayout_78.addWidget(self.volume_converted1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_78.addItem(spacerItem2)
        self.verticalLayout_64.addLayout(self.horizontalLayout_78)
        self.horizontalLayout_76.addLayout(self.verticalLayout_64)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem3)
        self.line_3 = QtWidgets.QFrame(self.pair1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_76.addWidget(self.line_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem4)
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.label_94 = QtWidgets.QLabel(self.pair1)
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_79.addWidget(self.label_94)
        self.high1 = QtWidgets.QLabel(self.pair1)
        self.high1.setObjectName("high1")
        self.horizontalLayout_79.addWidget(self.high1)
        self.high_converted1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.high_converted1.setFont(font)
        self.high_converted1.setObjectName("high_converted1")
        self.horizontalLayout_79.addWidget(self.high_converted1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_79.addItem(spacerItem5)
        self.verticalLayout_65.addLayout(self.horizontalLayout_79)
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.label_96 = QtWidgets.QLabel(self.pair1)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_80.addWidget(self.label_96)
        self.low1 = QtWidgets.QLabel(self.pair1)
        self.low1.setObjectName("low1")
        self.horizontalLayout_80.addWidget(self.low1)
        self.low_converted1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.low_converted1.setFont(font)
        self.low_converted1.setObjectName("low_converted1")
        self.horizontalLayout_80.addWidget(self.low_converted1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_80.addItem(spacerItem6)
        self.verticalLayout_65.addLayout(self.horizontalLayout_80)
        self.horizontalLayout_76.addLayout(self.verticalLayout_65)
        self.verticalLayout_63.addLayout(self.horizontalLayout_76)
        self.verticalLayout_62.addLayout(self.verticalLayout_63)
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.label_98 = QtWidgets.QLabel(self.pair1)
        self.label_98.setObjectName("label_98")
        self.horizontalLayout_82.addWidget(self.label_98, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_66.addLayout(self.horizontalLayout_82)
        self.buy_table1 = QtWidgets.QTableWidget(self.pair1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy_table1.sizePolicy().hasHeightForWidth())
        self.buy_table1.setSizePolicy(sizePolicy)
        self.buy_table1.setMinimumSize(QtCore.QSize(220, 75))
        self.buy_table1.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buy_table1.setLineWidth(1)
        self.buy_table1.setShowGrid(True)
        self.buy_table1.setObjectName("buy_table1")
        self.buy_table1.horizontalHeader().setVisible(False)
        self.buy_table1.horizontalHeader().setDefaultSectionSize(110)
        self.buy_table1.horizontalHeader().setHighlightSections(False)
        self.buy_table1.verticalHeader().setVisible(False)
        self.buy_table1.verticalHeader().setDefaultSectionSize(20)
        self.buy_table1.verticalHeader().setHighlightSections(False)
        self.verticalLayout_66.addWidget(self.buy_table1, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_81.addLayout(self.verticalLayout_66)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.label_99 = QtWidgets.QLabel(self.pair1)
        self.label_99.setObjectName("label_99")
        self.horizontalLayout_83.addWidget(self.label_99, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_67.addLayout(self.horizontalLayout_83)
        self.sell_table1 = QtWidgets.QTableWidget(self.pair1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sell_table1.sizePolicy().hasHeightForWidth())
        self.sell_table1.setSizePolicy(sizePolicy)
        self.sell_table1.setMinimumSize(QtCore.QSize(220, 75))
        self.sell_table1.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sell_table1.setShowGrid(True)
        self.sell_table1.setObjectName("sell_table1")
        self.sell_table1.horizontalHeader().setVisible(False)
        self.sell_table1.horizontalHeader().setDefaultSectionSize(110)
        self.sell_table1.horizontalHeader().setHighlightSections(False)
        self.sell_table1.verticalHeader().setVisible(False)
        self.sell_table1.verticalHeader().setDefaultSectionSize(20)
        self.sell_table1.verticalHeader().setHighlightSections(False)
        self.verticalLayout_67.addWidget(self.sell_table1)
        self.horizontalLayout_81.addLayout(self.verticalLayout_67)
        self.verticalLayout_62.addLayout(self.horizontalLayout_81)
        self.verticalLayout_61.addLayout(self.verticalLayout_62)
        self.verticalLayout_5.addWidget(self.pair1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.line_2 = QtWidgets.QFrame(self.pair_group1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.pair2 = QtWidgets.QWidget(self.pair_group1)
        self.pair2.setObjectName("pair2")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.pair2)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_67 = QtWidgets.QLabel(self.pair2)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_57.addWidget(self.label_67)
        self.pair_name2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pair_name2.setFont(font)
        self.pair_name2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pair_name2.setObjectName("pair_name2")
        self.horizontalLayout_57.addWidget(self.pair_name2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem9)
        self.label_3 = QtWidgets.QLabel(self.pair2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_57.addWidget(self.label_3)
        self.update_time2 = QtWidgets.QLabel(self.pair2)
        self.update_time2.setObjectName("update_time2")
        self.horizontalLayout_57.addWidget(self.update_time2)
        self.allert_symbol2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.allert_symbol2.setFont(font)
        self.allert_symbol2.setObjectName("allert_symbol2")
        self.horizontalLayout_57.addWidget(self.allert_symbol2)
        self.verticalLayout_49.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_68 = QtWidgets.QLabel(self.pair2)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_59.addWidget(self.label_68)
        self.price2 = QtWidgets.QLabel(self.pair2)
        self.price2.setObjectName("price2")
        self.horizontalLayout_59.addWidget(self.price2)
        self.price_converted2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.price_converted2.setFont(font)
        self.price_converted2.setObjectName("price_converted2")
        self.horizontalLayout_59.addWidget(self.price_converted2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem10)
        self.verticalLayout_50.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_70 = QtWidgets.QLabel(self.pair2)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_60.addWidget(self.label_70)
        self.volume2 = QtWidgets.QLabel(self.pair2)
        self.volume2.setObjectName("volume2")
        self.horizontalLayout_60.addWidget(self.volume2)
        self.volume_converted2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_converted2.setFont(font)
        self.volume_converted2.setObjectName("volume_converted2")
        self.horizontalLayout_60.addWidget(self.volume_converted2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem11)
        self.verticalLayout_50.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_58.addLayout(self.verticalLayout_50)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem12)
        self.line_4 = QtWidgets.QFrame(self.pair2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_58.addWidget(self.line_4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem13)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_72 = QtWidgets.QLabel(self.pair2)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_61.addWidget(self.label_72)
        self.high2 = QtWidgets.QLabel(self.pair2)
        self.high2.setObjectName("high2")
        self.horizontalLayout_61.addWidget(self.high2)
        self.high_converted2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.high_converted2.setFont(font)
        self.high_converted2.setObjectName("high_converted2")
        self.horizontalLayout_61.addWidget(self.high_converted2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem14)
        self.verticalLayout_51.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_74 = QtWidgets.QLabel(self.pair2)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_62.addWidget(self.label_74)
        self.low2 = QtWidgets.QLabel(self.pair2)
        self.low2.setObjectName("low2")
        self.horizontalLayout_62.addWidget(self.low2)
        self.low_converted2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.low_converted2.setFont(font)
        self.low_converted2.setObjectName("low_converted2")
        self.horizontalLayout_62.addWidget(self.low_converted2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(spacerItem15)
        self.verticalLayout_51.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_58.addLayout(self.verticalLayout_51)
        self.verticalLayout_49.addLayout(self.horizontalLayout_58)
        self.verticalLayout_48.addLayout(self.verticalLayout_49)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.label_76 = QtWidgets.QLabel(self.pair2)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_64.addWidget(self.label_76, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_52.addLayout(self.horizontalLayout_64)
        self.buy_table2 = QtWidgets.QTableWidget(self.pair2)
        self.buy_table2.setMinimumSize(QtCore.QSize(220, 75))
        self.buy_table2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buy_table2.setShowGrid(True)
        self.buy_table2.setObjectName("buy_table2")
        self.buy_table2.horizontalHeader().setVisible(False)
        self.buy_table2.horizontalHeader().setDefaultSectionSize(110)
        self.buy_table2.horizontalHeader().setHighlightSections(False)
        self.buy_table2.verticalHeader().setVisible(False)
        self.buy_table2.verticalHeader().setDefaultSectionSize(20)
        self.buy_table2.verticalHeader().setHighlightSections(False)
        self.verticalLayout_52.addWidget(self.buy_table2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_63.addLayout(self.verticalLayout_52)
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.label_77 = QtWidgets.QLabel(self.pair2)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_65.addWidget(self.label_77, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_53.addLayout(self.horizontalLayout_65)
        self.sell_table2 = QtWidgets.QTableWidget(self.pair2)
        self.sell_table2.setMinimumSize(QtCore.QSize(220, 75))
        self.sell_table2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sell_table2.setShowGrid(True)
        self.sell_table2.setObjectName("sell_table2")
        self.sell_table2.horizontalHeader().setVisible(False)
        self.sell_table2.horizontalHeader().setDefaultSectionSize(110)
        self.sell_table2.horizontalHeader().setHighlightSections(False)
        self.sell_table2.verticalHeader().setVisible(False)
        self.sell_table2.verticalHeader().setDefaultSectionSize(20)
        self.sell_table2.verticalHeader().setHighlightSections(False)
        self.verticalLayout_53.addWidget(self.sell_table2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_63.addLayout(self.verticalLayout_53)
        self.verticalLayout_48.addLayout(self.horizontalLayout_63)
        self.verticalLayout_47.addLayout(self.verticalLayout_48)
        self.verticalLayout_5.addWidget(self.pair2)
        self.horizontalLayout.addWidget(self.pair_group1)
        self.pair_group2 = QtWidgets.QGroupBox(self.centralwidget)
        self.pair_group2.setObjectName("pair_group2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pair_group2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pair3 = QtWidgets.QWidget(self.pair_group2)
        self.pair3.setObjectName("pair3")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.pair3)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.label_78 = QtWidgets.QLabel(self.pair3)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_66.addWidget(self.label_78)
        self.pair_name3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.pair_name3.setFont(font)
        self.pair_name3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pair_name3.setObjectName("pair_name3")
        self.horizontalLayout_66.addWidget(self.pair_name3)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem16)
        self.label_2 = QtWidgets.QLabel(self.pair3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_66.addWidget(self.label_2)
        self.update_time3 = QtWidgets.QLabel(self.pair3)
        self.update_time3.setObjectName("update_time3")
        self.horizontalLayout_66.addWidget(self.update_time3)
        self.allert_symbol3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.allert_symbol3.setFont(font)
        self.allert_symbol3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.allert_symbol3.setAutoFillBackground(False)
        self.allert_symbol3.setStyleSheet("label9{rgb(239, 41, 41)}")
        self.allert_symbol3.setObjectName("allert_symbol3")
        self.horizontalLayout_66.addWidget(self.allert_symbol3)
        self.verticalLayout_56.addLayout(self.horizontalLayout_66)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_79 = QtWidgets.QLabel(self.pair3)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_68.addWidget(self.label_79)
        self.price3 = QtWidgets.QLabel(self.pair3)
        self.price3.setObjectName("price3")
        self.horizontalLayout_68.addWidget(self.price3)
        self.price_converted3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.price_converted3.setFont(font)
        self.price_converted3.setObjectName("price_converted3")
        self.horizontalLayout_68.addWidget(self.price_converted3)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_68.addItem(spacerItem17)
        self.verticalLayout_57.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_81 = QtWidgets.QLabel(self.pair3)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_69.addWidget(self.label_81)
        self.volume3 = QtWidgets.QLabel(self.pair3)
        self.volume3.setObjectName("volume3")
        self.horizontalLayout_69.addWidget(self.volume3)
        self.volume_converted3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_converted3.setFont(font)
        self.volume_converted3.setObjectName("volume_converted3")
        self.horizontalLayout_69.addWidget(self.volume_converted3)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_69.addItem(spacerItem18)
        self.verticalLayout_57.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_67.addLayout(self.verticalLayout_57)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem19)
        self.line_6 = QtWidgets.QFrame(self.pair3)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_67.addWidget(self.line_6)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem20)
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.label_83 = QtWidgets.QLabel(self.pair3)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_70.addWidget(self.label_83)
        self.high3 = QtWidgets.QLabel(self.pair3)
        self.high3.setObjectName("high3")
        self.horizontalLayout_70.addWidget(self.high3)
        self.high_converted3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.high_converted3.setFont(font)
        self.high_converted3.setObjectName("high_converted3")
        self.horizontalLayout_70.addWidget(self.high_converted3)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_70.addItem(spacerItem21)
        self.verticalLayout_58.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_85 = QtWidgets.QLabel(self.pair3)
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_71.addWidget(self.label_85)
        self.low3 = QtWidgets.QLabel(self.pair3)
        self.low3.setObjectName("low3")
        self.horizontalLayout_71.addWidget(self.low3)
        self.low_converted3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.low_converted3.setFont(font)
        self.low_converted3.setObjectName("low_converted3")
        self.horizontalLayout_71.addWidget(self.low_converted3)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem22)
        self.verticalLayout_58.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_67.addLayout(self.verticalLayout_58)
        self.verticalLayout_56.addLayout(self.horizontalLayout_67)
        self.verticalLayout_55.addLayout(self.verticalLayout_56)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.label_87 = QtWidgets.QLabel(self.pair3)
        self.label_87.setObjectName("label_87")
        self.horizontalLayout_73.addWidget(self.label_87, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_59.addLayout(self.horizontalLayout_73)
        self.buy_table3 = QtWidgets.QTableWidget(self.pair3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy_table3.sizePolicy().hasHeightForWidth())
        self.buy_table3.setSizePolicy(sizePolicy)
        self.buy_table3.setMinimumSize(QtCore.QSize(220, 75))
        self.buy_table3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buy_table3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.buy_table3.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.buy_table3.setShowGrid(True)
        self.buy_table3.setGridStyle(QtCore.Qt.SolidLine)
        self.buy_table3.setObjectName("buy_table3")
        self.buy_table3.horizontalHeader().setVisible(False)
        self.buy_table3.horizontalHeader().setDefaultSectionSize(110)
        self.buy_table3.horizontalHeader().setHighlightSections(False)
        self.buy_table3.verticalHeader().setVisible(False)
        self.buy_table3.verticalHeader().setDefaultSectionSize(20)
        self.buy_table3.verticalHeader().setHighlightSections(False)
        self.verticalLayout_59.addWidget(self.buy_table3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_72.addLayout(self.verticalLayout_59)
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.label_88 = QtWidgets.QLabel(self.pair3)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_74.addWidget(self.label_88, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_60.addLayout(self.horizontalLayout_74)
        self.sell_table3 = QtWidgets.QTableWidget(self.pair3)
        self.sell_table3.setMinimumSize(QtCore.QSize(220, 75))
        self.sell_table3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sell_table3.setShowGrid(True)
        self.sell_table3.setObjectName("sell_table3")
        self.sell_table3.horizontalHeader().setVisible(False)
        self.sell_table3.horizontalHeader().setDefaultSectionSize(110)
        self.sell_table3.horizontalHeader().setHighlightSections(False)
        self.sell_table3.verticalHeader().setVisible(False)
        self.sell_table3.verticalHeader().setDefaultSectionSize(20)
        self.sell_table3.verticalHeader().setHighlightSections(False)
        self.verticalLayout_60.addWidget(self.sell_table3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_72.addLayout(self.verticalLayout_60)
        self.verticalLayout_55.addLayout(self.horizontalLayout_72)
        self.verticalLayout_54.addLayout(self.verticalLayout_55)
        self.verticalLayout_4.addWidget(self.pair3)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem23)
        self.line = QtWidgets.QFrame(self.pair_group2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem24)
        self.pair4 = QtWidgets.QWidget(self.pair_group2)
        self.pair4.setObjectName("pair4")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.pair4)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_45 = QtWidgets.QLabel(self.pair4)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_39.addWidget(self.label_45)
        self.pair_name4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pair_name4.setFont(font)
        self.pair_name4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pair_name4.setObjectName("pair_name4")
        self.horizontalLayout_39.addWidget(self.pair_name4)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem25)
        self.label_5 = QtWidgets.QLabel(self.pair4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_39.addWidget(self.label_5)
        self.update_time4 = QtWidgets.QLabel(self.pair4)
        self.update_time4.setObjectName("update_time4")
        self.horizontalLayout_39.addWidget(self.update_time4)
        self.allert_symbol4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.allert_symbol4.setFont(font)
        self.allert_symbol4.setObjectName("allert_symbol4")
        self.horizontalLayout_39.addWidget(self.allert_symbol4)
        self.verticalLayout_35.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_46 = QtWidgets.QLabel(self.pair4)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_41.addWidget(self.label_46)
        self.price4 = QtWidgets.QLabel(self.pair4)
        self.price4.setObjectName("price4")
        self.horizontalLayout_41.addWidget(self.price4)
        self.price_converted4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.price_converted4.setFont(font)
        self.price_converted4.setObjectName("price_converted4")
        self.horizontalLayout_41.addWidget(self.price_converted4)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem26)
        self.verticalLayout_36.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_48 = QtWidgets.QLabel(self.pair4)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_42.addWidget(self.label_48)
        self.volume4 = QtWidgets.QLabel(self.pair4)
        self.volume4.setObjectName("volume4")
        self.horizontalLayout_42.addWidget(self.volume4)
        self.volume_converted4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_converted4.setFont(font)
        self.volume_converted4.setObjectName("volume_converted4")
        self.horizontalLayout_42.addWidget(self.volume_converted4)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem27)
        self.verticalLayout_36.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_40.addLayout(self.verticalLayout_36)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem28)
        self.line_5 = QtWidgets.QFrame(self.pair4)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_40.addWidget(self.line_5)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem29)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_50 = QtWidgets.QLabel(self.pair4)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_43.addWidget(self.label_50)
        self.high4 = QtWidgets.QLabel(self.pair4)
        self.high4.setObjectName("high4")
        self.horizontalLayout_43.addWidget(self.high4)
        self.high_converted4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.high_converted4.setFont(font)
        self.high_converted4.setObjectName("high_converted4")
        self.horizontalLayout_43.addWidget(self.high_converted4)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem30)
        self.verticalLayout_37.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_52 = QtWidgets.QLabel(self.pair4)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_44.addWidget(self.label_52)
        self.low4 = QtWidgets.QLabel(self.pair4)
        self.low4.setObjectName("low4")
        self.horizontalLayout_44.addWidget(self.low4)
        self.low_converted4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.low_converted4.setFont(font)
        self.low_converted4.setObjectName("low_converted4")
        self.horizontalLayout_44.addWidget(self.low_converted4)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem31)
        self.verticalLayout_37.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_40.addLayout(self.verticalLayout_37)
        self.verticalLayout_35.addLayout(self.horizontalLayout_40)
        self.verticalLayout_34.addLayout(self.verticalLayout_35)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_54 = QtWidgets.QLabel(self.pair4)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_46.addWidget(self.label_54, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_38.addLayout(self.horizontalLayout_46)
        self.buy_table4 = QtWidgets.QTableWidget(self.pair4)
        self.buy_table4.setMinimumSize(QtCore.QSize(220, 75))
        self.buy_table4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buy_table4.setShowGrid(True)
        self.buy_table4.setObjectName("buy_table4")
        self.buy_table4.horizontalHeader().setVisible(False)
        self.buy_table4.horizontalHeader().setDefaultSectionSize(110)
        self.buy_table4.horizontalHeader().setHighlightSections(False)
        self.buy_table4.verticalHeader().setVisible(False)
        self.buy_table4.verticalHeader().setDefaultSectionSize(20)
        self.buy_table4.verticalHeader().setHighlightSections(False)
        self.verticalLayout_38.addWidget(self.buy_table4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_45.addLayout(self.verticalLayout_38)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_55 = QtWidgets.QLabel(self.pair4)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_47.addWidget(self.label_55, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_39.addLayout(self.horizontalLayout_47)
        self.sell_table4 = QtWidgets.QTableWidget(self.pair4)
        self.sell_table4.setMinimumSize(QtCore.QSize(220, 75))
        self.sell_table4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sell_table4.setShowGrid(True)
        self.sell_table4.setObjectName("sell_table4")
        self.sell_table4.horizontalHeader().setVisible(False)
        self.sell_table4.horizontalHeader().setDefaultSectionSize(110)
        self.sell_table4.horizontalHeader().setHighlightSections(False)
        self.sell_table4.verticalHeader().setVisible(False)
        self.sell_table4.verticalHeader().setDefaultSectionSize(20)
        self.sell_table4.verticalHeader().setHighlightSections(False)
        self.verticalLayout_39.addWidget(self.sell_table4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_45.addLayout(self.verticalLayout_39)
        self.verticalLayout_34.addLayout(self.horizontalLayout_45)
        self.verticalLayout_33.addLayout(self.verticalLayout_34)
        self.verticalLayout_4.addWidget(self.pair4)
        self.horizontalLayout.addWidget(self.pair_group2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1078, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuSettings_2 = QtWidgets.QMenu(self.menuSettings)
        self.menuSettings_2.setObjectName("menuSettings_2")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAllSettings = QtWidgets.QAction(MainWindow)
        self.actionAllSettings.setObjectName("actionAllSettings")
        self.actionAllerts = QtWidgets.QAction(MainWindow)
        self.actionAllerts.setObjectName("actionAllerts")
        self.actionWindow = QtWidgets.QAction(MainWindow)
        self.actionWindow.setObjectName("actionWindow")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPairs = QtWidgets.QAction(MainWindow)
        self.actionPairs.setObjectName("actionPairs")
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setObjectName("actionReport")
        self.actionLogging = QtWidgets.QAction(MainWindow)
        self.actionLogging.setObjectName("actionLogging")
        self.menuSettings_2.addSeparator()
        self.menuSettings_2.addAction(self.actionAllSettings)
        self.menuSettings_2.addSeparator()
        self.menuSettings_2.addAction(self.actionPairs)
        self.menuSettings_2.addAction(self.actionWindow)
        self.menuSettings_2.addAction(self.actionAllerts)
        self.menuSettings_2.addSeparator()
        self.menuSettings_2.addAction(self.actionLogging)
        self.menuSettings.addAction(self.menuSettings_2.menuAction())
        self.menuSettings.addAction(self.actionReport)
        self.menuSettings.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pair_group1.setTitle(_translate("MainWindow", "KuCoin:"))
        self.label_89.setText(_translate("MainWindow", "Pair:"))
        self.pair_name1.setText(_translate("MainWindow", "BTC-TRTL"))
        self.label.setText(_translate("MainWindow", "Updated:"))
        self.update_time1.setText(_translate("MainWindow", "TextLabel"))
        self.allert_symbol1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#cc0000;\">!</span></p></body></html>"))
        self.label_90.setText(_translate("MainWindow", "Price:"))
        self.price1.setText(_translate("MainWindow", "888.88888"))
        self.price_converted1.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_92.setText(_translate("MainWindow", "Volume:"))
        self.volume1.setText(_translate("MainWindow", "888.88888"))
        self.volume_converted1.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_94.setText(_translate("MainWindow", "High:"))
        self.high1.setText(_translate("MainWindow", "888.88888"))
        self.high_converted1.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_96.setText(_translate("MainWindow", "Low:"))
        self.low1.setText(_translate("MainWindow", "888.88888"))
        self.low_converted1.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_98.setText(_translate("MainWindow", "Buy:"))
        self.label_99.setText(_translate("MainWindow", "Sell:"))
        self.label_67.setText(_translate("MainWindow", "Pair:"))
        self.pair_name2.setText(_translate("MainWindow", "BTC-TRTL"))
        self.label_3.setText(_translate("MainWindow", "Updated:"))
        self.update_time2.setText(_translate("MainWindow", "TextLabel"))
        self.allert_symbol2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#cc0000;\">!</span></p></body></html>"))
        self.label_68.setText(_translate("MainWindow", "Price:"))
        self.price2.setText(_translate("MainWindow", "888.88888"))
        self.price_converted2.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_70.setText(_translate("MainWindow", "Volume:"))
        self.volume2.setText(_translate("MainWindow", "888.88888"))
        self.volume_converted2.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_72.setText(_translate("MainWindow", "High:"))
        self.high2.setText(_translate("MainWindow", "888.88888"))
        self.high_converted2.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_74.setText(_translate("MainWindow", "Low:"))
        self.low2.setText(_translate("MainWindow", "888.88888"))
        self.low_converted2.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_76.setText(_translate("MainWindow", "Buy:"))
        self.label_77.setText(_translate("MainWindow", "Sell:"))
        self.pair_group2.setTitle(_translate("MainWindow", "TradeOgre:"))
        self.label_78.setText(_translate("MainWindow", "Pair:"))
        self.pair_name3.setText(_translate("MainWindow", "BTC-TRTL"))
        self.label_2.setText(_translate("MainWindow", "Updated:"))
        self.update_time3.setText(_translate("MainWindow", "TextLabel"))
        self.allert_symbol3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#cc0000;\">!</span></p></body></html>"))
        self.label_79.setText(_translate("MainWindow", "Price:"))
        self.price3.setText(_translate("MainWindow", "888.88888"))
        self.price_converted3.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_81.setText(_translate("MainWindow", "Volume:"))
        self.volume3.setText(_translate("MainWindow", "8888.88888"))
        self.volume_converted3.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_83.setText(_translate("MainWindow", "High:"))
        self.high3.setText(_translate("MainWindow", "888.88888"))
        self.high_converted3.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_85.setText(_translate("MainWindow", "Low:"))
        self.low3.setText(_translate("MainWindow", "888.88888"))
        self.low_converted3.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_87.setText(_translate("MainWindow", "Buy:"))
        self.label_88.setText(_translate("MainWindow", "Sell:"))
        self.label_45.setText(_translate("MainWindow", "Pair:"))
        self.pair_name4.setText(_translate("MainWindow", "BTC-TRTL"))
        self.label_5.setText(_translate("MainWindow", "Updated:"))
        self.update_time4.setText(_translate("MainWindow", "TextLabel"))
        self.allert_symbol4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#cc0000;\">!</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "Price:"))
        self.price4.setText(_translate("MainWindow", "888.88888"))
        self.price_converted4.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_48.setText(_translate("MainWindow", "Volume:"))
        self.volume4.setText(_translate("MainWindow", "888.88888"))
        self.volume_converted4.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_50.setText(_translate("MainWindow", "High:"))
        self.high4.setText(_translate("MainWindow", "888.88888"))
        self.high_converted4.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_52.setText(_translate("MainWindow", "Low:"))
        self.low4.setText(_translate("MainWindow", "888.88888"))
        self.low_converted4.setText(_translate("MainWindow", "(111.11111 BTC)"))
        self.label_54.setText(_translate("MainWindow", "Buy:"))
        self.label_55.setText(_translate("MainWindow", "Sell:"))
        self.menuSettings.setTitle(_translate("MainWindow", "Menu"))
        self.menuSettings_2.setTitle(_translate("MainWindow", "Settings"))
        self.actionAllSettings.setText(_translate("MainWindow", "All settings"))
        self.actionAllerts.setText(_translate("MainWindow", "Allerts"))
        self.actionWindow.setText(_translate("MainWindow", "Window"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionPairs.setText(_translate("MainWindow", "Pairs"))
        self.actionReport.setText(_translate("MainWindow", "Report"))
        self.actionLogging.setText(_translate("MainWindow", "Logging"))
