# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 672)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 39, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 32, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 19, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 17, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 19, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 13, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 39, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 32, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 19, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 17, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 19, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(11, 13, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 19, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 39, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 32, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 19, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 17, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 19, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 19, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/gui_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/gui_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/gui_icon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/gui_icon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/gui_icon.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/gui_icon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/gui_icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/gui_icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar_widget = QtWidgets.QWidget(self.centralwidget)
        self.toolbar_widget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.toolbar_widget.setObjectName("toolbar_widget")
        self.toolbar = QtWidgets.QVBoxLayout(self.toolbar_widget)
        self.toolbar.setContentsMargins(0, 0, 0, 0)
        self.toolbar.setSpacing(0)
        self.toolbar.setObjectName("toolbar")
        self.toolbar_2 = QtWidgets.QWidget(self.toolbar_widget)
        self.toolbar_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.toolbar_2.setObjectName("toolbar_2")
        self.toolbar1 = QtWidgets.QHBoxLayout(self.toolbar_2)
        self.toolbar1.setContentsMargins(3, 5, 3, 5)
        self.toolbar1.setSpacing(0)
        self.toolbar1.setObjectName("toolbar1")
        self.update_button = QtWidgets.QPushButton(self.toolbar_2)
        self.update_button.setObjectName("update_button")
        self.toolbar1.addWidget(self.update_button)
        self.line_7 = QtWidgets.QFrame(self.toolbar_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.toolbar1.addWidget(self.line_7)
        self.pushButton_3 = QtWidgets.QPushButton(self.toolbar_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.toolbar1.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbar1.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.toolbar_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.toolbar1.addWidget(self.pushButton_2)
        self.toolbar.addWidget(self.toolbar_2)
        self.line_8 = QtWidgets.QFrame(self.toolbar_widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(23, 26, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.line_8.setPalette(palette)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.toolbar.addWidget(self.line_8)
        self.verticalLayout.addWidget(self.toolbar_widget)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout.addWidget(self.line_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pair_group1 = QtWidgets.QGroupBox(self.centralwidget)
        self.pair_group1.setObjectName("pair_group1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pair_group1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pair1 = QtWidgets.QWidget(self.pair_group1)
        self.pair1.setObjectName("pair1")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.pair1)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.verticalLayout_62 = QtWidgets.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.label_89 = QtWidgets.QLabel(self.pair1)
        self.label_89.setObjectName("label_89")
        self.horizontalLayout_75.addWidget(self.label_89)
        self.pair_name1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pair_name1.setFont(font)
        self.pair_name1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pair_name1.setObjectName("pair_name1")
        self.horizontalLayout_75.addWidget(self.pair_name1)
        self.browser_button1 = QtWidgets.QPushButton(self.pair1)
        self.browser_button1.setMaximumSize(QtCore.QSize(20, 20))
        self.browser_button1.setObjectName("browser_button1")
        self.horizontalLayout_75.addWidget(self.browser_button1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.pair1)
        self.label.setObjectName("label")
        self.horizontalLayout_75.addWidget(self.label)
        self.update_time1 = QtWidgets.QLabel(self.pair1)
        self.update_time1.setObjectName("update_time1")
        self.horizontalLayout_75.addWidget(self.update_time1)
        self.allert_symbol1 = QtWidgets.QLabel(self.pair1)
        self.allert_symbol1.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.allert_symbol1.setFont(font)
        self.allert_symbol1.setObjectName("allert_symbol1")
        self.horizontalLayout_75.addWidget(self.allert_symbol1)
        self.verticalLayout_63.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.label_90 = QtWidgets.QLabel(self.pair1)
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_77.addWidget(self.label_90)
        self.price1 = QtWidgets.QLabel(self.pair1)
        self.price1.setObjectName("price1")
        self.horizontalLayout_77.addWidget(self.price1)
        self.price_converted1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.price_converted1.setFont(font)
        self.price_converted1.setText("")
        self.price_converted1.setObjectName("price_converted1")
        self.horizontalLayout_77.addWidget(self.price_converted1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem2)
        self.verticalLayout_64.addLayout(self.horizontalLayout_77)
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.label_92 = QtWidgets.QLabel(self.pair1)
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_78.addWidget(self.label_92)
        self.volume1 = QtWidgets.QLabel(self.pair1)
        self.volume1.setObjectName("volume1")
        self.horizontalLayout_78.addWidget(self.volume1)
        self.volume_converted1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_converted1.setFont(font)
        self.volume_converted1.setText("")
        self.volume_converted1.setObjectName("volume_converted1")
        self.horizontalLayout_78.addWidget(self.volume_converted1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_78.addItem(spacerItem3)
        self.verticalLayout_64.addLayout(self.horizontalLayout_78)
        self.horizontalLayout_76.addLayout(self.verticalLayout_64)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem4)
        self.line_3 = QtWidgets.QFrame(self.pair1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_76.addWidget(self.line_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem5)
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.label_94 = QtWidgets.QLabel(self.pair1)
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_79.addWidget(self.label_94)
        self.high1 = QtWidgets.QLabel(self.pair1)
        self.high1.setObjectName("high1")
        self.horizontalLayout_79.addWidget(self.high1)
        self.high_converted1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.high_converted1.setFont(font)
        self.high_converted1.setText("")
        self.high_converted1.setObjectName("high_converted1")
        self.horizontalLayout_79.addWidget(self.high_converted1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_79.addItem(spacerItem6)
        self.verticalLayout_65.addLayout(self.horizontalLayout_79)
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.label_96 = QtWidgets.QLabel(self.pair1)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_80.addWidget(self.label_96)
        self.low1 = QtWidgets.QLabel(self.pair1)
        self.low1.setObjectName("low1")
        self.horizontalLayout_80.addWidget(self.low1)
        self.low_converted1 = QtWidgets.QLabel(self.pair1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.low_converted1.setFont(font)
        self.low_converted1.setText("")
        self.low_converted1.setObjectName("low_converted1")
        self.horizontalLayout_80.addWidget(self.low_converted1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_80.addItem(spacerItem7)
        self.verticalLayout_65.addLayout(self.horizontalLayout_80)
        self.horizontalLayout_76.addLayout(self.verticalLayout_65)
        self.verticalLayout_63.addLayout(self.horizontalLayout_76)
        self.verticalLayout_62.addLayout(self.verticalLayout_63)
        self.orders1 = QtWidgets.QWidget(self.pair1)
        self.orders1.setObjectName("orders1")
        self.orders1_ = QtWidgets.QHBoxLayout(self.orders1)
        self.orders1_.setObjectName("orders1_")
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.label_99 = QtWidgets.QLabel(self.orders1)
        self.label_99.setObjectName("label_99")
        self.horizontalLayout_83.addWidget(self.label_99, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_67.addLayout(self.horizontalLayout_83)
        self.sell_table1 = QtWidgets.QTableWidget(self.orders1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sell_table1.sizePolicy().hasHeightForWidth())
        self.sell_table1.setSizePolicy(sizePolicy)
        self.sell_table1.setMinimumSize(QtCore.QSize(220, 75))
        self.sell_table1.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sell_table1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sell_table1.setShowGrid(True)
        self.sell_table1.setObjectName("sell_table1")
        self.sell_table1.setColumnCount(0)
        self.sell_table1.setRowCount(0)
        self.sell_table1.horizontalHeader().setVisible(False)
        self.sell_table1.horizontalHeader().setDefaultSectionSize(110)
        self.sell_table1.horizontalHeader().setHighlightSections(False)
        self.sell_table1.verticalHeader().setVisible(False)
        self.sell_table1.verticalHeader().setDefaultSectionSize(20)
        self.sell_table1.verticalHeader().setHighlightSections(False)
        self.verticalLayout_67.addWidget(self.sell_table1)
        self.orders1_.addLayout(self.verticalLayout_67)
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.label_98 = QtWidgets.QLabel(self.orders1)
        self.label_98.setObjectName("label_98")
        self.horizontalLayout_82.addWidget(self.label_98, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_66.addLayout(self.horizontalLayout_82)
        self.buy_table1 = QtWidgets.QTableWidget(self.orders1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy_table1.sizePolicy().hasHeightForWidth())
        self.buy_table1.setSizePolicy(sizePolicy)
        self.buy_table1.setMinimumSize(QtCore.QSize(220, 75))
        self.buy_table1.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buy_table1.setLineWidth(1)
        self.buy_table1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.buy_table1.setShowGrid(True)
        self.buy_table1.setObjectName("buy_table1")
        self.buy_table1.setColumnCount(0)
        self.buy_table1.setRowCount(0)
        self.buy_table1.horizontalHeader().setVisible(False)
        self.buy_table1.horizontalHeader().setDefaultSectionSize(110)
        self.buy_table1.horizontalHeader().setHighlightSections(False)
        self.buy_table1.verticalHeader().setVisible(False)
        self.buy_table1.verticalHeader().setDefaultSectionSize(20)
        self.buy_table1.verticalHeader().setHighlightSections(False)
        self.verticalLayout_66.addWidget(self.buy_table1, 0, QtCore.Qt.AlignHCenter)
        self.orders1_.addLayout(self.verticalLayout_66)
        self.verticalLayout_62.addWidget(self.orders1)
        self.verticalLayout_61.addLayout(self.verticalLayout_62)
        self.verticalLayout_5.addWidget(self.pair1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.line_2 = QtWidgets.QFrame(self.pair_group1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.pair2 = QtWidgets.QWidget(self.pair_group1)
        self.pair2.setObjectName("pair2")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.pair2)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_67 = QtWidgets.QLabel(self.pair2)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_57.addWidget(self.label_67)
        self.pair_name2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pair_name2.setFont(font)
        self.pair_name2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pair_name2.setObjectName("pair_name2")
        self.horizontalLayout_57.addWidget(self.pair_name2)
        self.browser_button2 = QtWidgets.QPushButton(self.pair2)
        self.browser_button2.setMaximumSize(QtCore.QSize(20, 20))
        self.browser_button2.setObjectName("browser_button2")
        self.horizontalLayout_57.addWidget(self.browser_button2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem10)
        self.label_3 = QtWidgets.QLabel(self.pair2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_57.addWidget(self.label_3)
        self.update_time2 = QtWidgets.QLabel(self.pair2)
        self.update_time2.setObjectName("update_time2")
        self.horizontalLayout_57.addWidget(self.update_time2)
        self.allert_symbol2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.allert_symbol2.setFont(font)
        self.allert_symbol2.setObjectName("allert_symbol2")
        self.horizontalLayout_57.addWidget(self.allert_symbol2)
        self.verticalLayout_49.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_68 = QtWidgets.QLabel(self.pair2)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_59.addWidget(self.label_68)
        self.price2 = QtWidgets.QLabel(self.pair2)
        self.price2.setObjectName("price2")
        self.horizontalLayout_59.addWidget(self.price2)
        self.price_converted2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.price_converted2.setFont(font)
        self.price_converted2.setText("")
        self.price_converted2.setObjectName("price_converted2")
        self.horizontalLayout_59.addWidget(self.price_converted2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem11)
        self.verticalLayout_50.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_70 = QtWidgets.QLabel(self.pair2)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_60.addWidget(self.label_70)
        self.volume2 = QtWidgets.QLabel(self.pair2)
        self.volume2.setObjectName("volume2")
        self.horizontalLayout_60.addWidget(self.volume2)
        self.volume_converted2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_converted2.setFont(font)
        self.volume_converted2.setText("")
        self.volume_converted2.setObjectName("volume_converted2")
        self.horizontalLayout_60.addWidget(self.volume_converted2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem12)
        self.verticalLayout_50.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_58.addLayout(self.verticalLayout_50)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem13)
        self.line_4 = QtWidgets.QFrame(self.pair2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_58.addWidget(self.line_4)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem14)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_72 = QtWidgets.QLabel(self.pair2)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_61.addWidget(self.label_72)
        self.high2 = QtWidgets.QLabel(self.pair2)
        self.high2.setObjectName("high2")
        self.horizontalLayout_61.addWidget(self.high2)
        self.high_converted2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.high_converted2.setFont(font)
        self.high_converted2.setText("")
        self.high_converted2.setObjectName("high_converted2")
        self.horizontalLayout_61.addWidget(self.high_converted2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem15)
        self.verticalLayout_51.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_74 = QtWidgets.QLabel(self.pair2)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_62.addWidget(self.label_74)
        self.low2 = QtWidgets.QLabel(self.pair2)
        self.low2.setObjectName("low2")
        self.horizontalLayout_62.addWidget(self.low2)
        self.low_converted2 = QtWidgets.QLabel(self.pair2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.low_converted2.setFont(font)
        self.low_converted2.setText("")
        self.low_converted2.setObjectName("low_converted2")
        self.horizontalLayout_62.addWidget(self.low_converted2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(spacerItem16)
        self.verticalLayout_51.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_58.addLayout(self.verticalLayout_51)
        self.verticalLayout_49.addLayout(self.horizontalLayout_58)
        self.verticalLayout_48.addLayout(self.verticalLayout_49)
        self.orders2 = QtWidgets.QWidget(self.pair2)
        self.orders2.setObjectName("orders2")
        self.orders2_ = QtWidgets.QHBoxLayout(self.orders2)
        self.orders2_.setObjectName("orders2_")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.label_77 = QtWidgets.QLabel(self.orders2)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_65.addWidget(self.label_77, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_53.addLayout(self.horizontalLayout_65)
        self.sell_table2 = QtWidgets.QTableWidget(self.orders2)
        self.sell_table2.setMinimumSize(QtCore.QSize(220, 75))
        self.sell_table2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sell_table2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sell_table2.setShowGrid(True)
        self.sell_table2.setObjectName("sell_table2")
        self.sell_table2.setColumnCount(0)
        self.sell_table2.setRowCount(0)
        self.sell_table2.horizontalHeader().setVisible(False)
        self.sell_table2.horizontalHeader().setDefaultSectionSize(110)
        self.sell_table2.horizontalHeader().setHighlightSections(False)
        self.sell_table2.verticalHeader().setVisible(False)
        self.sell_table2.verticalHeader().setDefaultSectionSize(20)
        self.sell_table2.verticalHeader().setHighlightSections(False)
        self.verticalLayout_53.addWidget(self.sell_table2, 0, QtCore.Qt.AlignHCenter)
        self.orders2_.addLayout(self.verticalLayout_53)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.label_76 = QtWidgets.QLabel(self.orders2)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_64.addWidget(self.label_76, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_52.addLayout(self.horizontalLayout_64)
        self.buy_table2 = QtWidgets.QTableWidget(self.orders2)
        self.buy_table2.setMinimumSize(QtCore.QSize(220, 75))
        self.buy_table2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buy_table2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.buy_table2.setShowGrid(True)
        self.buy_table2.setObjectName("buy_table2")
        self.buy_table2.setColumnCount(0)
        self.buy_table2.setRowCount(0)
        self.buy_table2.horizontalHeader().setVisible(False)
        self.buy_table2.horizontalHeader().setDefaultSectionSize(110)
        self.buy_table2.horizontalHeader().setHighlightSections(False)
        self.buy_table2.verticalHeader().setVisible(False)
        self.buy_table2.verticalHeader().setDefaultSectionSize(20)
        self.buy_table2.verticalHeader().setHighlightSections(False)
        self.verticalLayout_52.addWidget(self.buy_table2, 0, QtCore.Qt.AlignHCenter)
        self.orders2_.addLayout(self.verticalLayout_52)
        self.verticalLayout_48.addWidget(self.orders2)
        self.verticalLayout_47.addLayout(self.verticalLayout_48)
        self.verticalLayout_5.addWidget(self.pair2)
        self.horizontalLayout_3.addWidget(self.pair_group1)
        self.pair_group2 = QtWidgets.QGroupBox(self.centralwidget)
        self.pair_group2.setObjectName("pair_group2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pair_group2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pair3 = QtWidgets.QWidget(self.pair_group2)
        self.pair3.setObjectName("pair3")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.pair3)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.label_78 = QtWidgets.QLabel(self.pair3)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_66.addWidget(self.label_78)
        self.pair_name3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.pair_name3.setFont(font)
        self.pair_name3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pair_name3.setObjectName("pair_name3")
        self.horizontalLayout_66.addWidget(self.pair_name3)
        self.browser_button3 = QtWidgets.QPushButton(self.pair3)
        self.browser_button3.setMaximumSize(QtCore.QSize(20, 20))
        self.browser_button3.setObjectName("browser_button3")
        self.horizontalLayout_66.addWidget(self.browser_button3)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem17)
        self.label_2 = QtWidgets.QLabel(self.pair3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_66.addWidget(self.label_2)
        self.update_time3 = QtWidgets.QLabel(self.pair3)
        self.update_time3.setObjectName("update_time3")
        self.horizontalLayout_66.addWidget(self.update_time3)
        self.allert_symbol3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.allert_symbol3.setFont(font)
        self.allert_symbol3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.allert_symbol3.setAutoFillBackground(False)
        self.allert_symbol3.setStyleSheet("label9{rgb(239, 41, 41)}")
        self.allert_symbol3.setObjectName("allert_symbol3")
        self.horizontalLayout_66.addWidget(self.allert_symbol3)
        self.verticalLayout_56.addLayout(self.horizontalLayout_66)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_79 = QtWidgets.QLabel(self.pair3)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_68.addWidget(self.label_79)
        self.price3 = QtWidgets.QLabel(self.pair3)
        self.price3.setObjectName("price3")
        self.horizontalLayout_68.addWidget(self.price3)
        self.price_converted3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.price_converted3.setFont(font)
        self.price_converted3.setText("")
        self.price_converted3.setObjectName("price_converted3")
        self.horizontalLayout_68.addWidget(self.price_converted3)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_68.addItem(spacerItem18)
        self.verticalLayout_57.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_81 = QtWidgets.QLabel(self.pair3)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_69.addWidget(self.label_81)
        self.volume3 = QtWidgets.QLabel(self.pair3)
        self.volume3.setObjectName("volume3")
        self.horizontalLayout_69.addWidget(self.volume3)
        self.volume_converted3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_converted3.setFont(font)
        self.volume_converted3.setText("")
        self.volume_converted3.setObjectName("volume_converted3")
        self.horizontalLayout_69.addWidget(self.volume_converted3)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_69.addItem(spacerItem19)
        self.verticalLayout_57.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_67.addLayout(self.verticalLayout_57)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem20)
        self.line_6 = QtWidgets.QFrame(self.pair3)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_67.addWidget(self.line_6)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem21)
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.label_83 = QtWidgets.QLabel(self.pair3)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_70.addWidget(self.label_83)
        self.high3 = QtWidgets.QLabel(self.pair3)
        self.high3.setObjectName("high3")
        self.horizontalLayout_70.addWidget(self.high3)
        self.high_converted3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.high_converted3.setFont(font)
        self.high_converted3.setText("")
        self.high_converted3.setObjectName("high_converted3")
        self.horizontalLayout_70.addWidget(self.high_converted3)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_70.addItem(spacerItem22)
        self.verticalLayout_58.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_85 = QtWidgets.QLabel(self.pair3)
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_71.addWidget(self.label_85)
        self.low3 = QtWidgets.QLabel(self.pair3)
        self.low3.setObjectName("low3")
        self.horizontalLayout_71.addWidget(self.low3)
        self.low_converted3 = QtWidgets.QLabel(self.pair3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.low_converted3.setFont(font)
        self.low_converted3.setText("")
        self.low_converted3.setObjectName("low_converted3")
        self.horizontalLayout_71.addWidget(self.low_converted3)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem23)
        self.verticalLayout_58.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_67.addLayout(self.verticalLayout_58)
        self.verticalLayout_56.addLayout(self.horizontalLayout_67)
        self.verticalLayout_55.addLayout(self.verticalLayout_56)
        self.orders3 = QtWidgets.QWidget(self.pair3)
        self.orders3.setObjectName("orders3")
        self.orders3_ = QtWidgets.QHBoxLayout(self.orders3)
        self.orders3_.setObjectName("orders3_")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.label_88 = QtWidgets.QLabel(self.orders3)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_74.addWidget(self.label_88, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_60.addLayout(self.horizontalLayout_74)
        self.sell_table3 = QtWidgets.QTableWidget(self.orders3)
        self.sell_table3.setMinimumSize(QtCore.QSize(220, 75))
        self.sell_table3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sell_table3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sell_table3.setShowGrid(True)
        self.sell_table3.setObjectName("sell_table3")
        self.sell_table3.setColumnCount(0)
        self.sell_table3.setRowCount(0)
        self.sell_table3.horizontalHeader().setVisible(False)
        self.sell_table3.horizontalHeader().setDefaultSectionSize(110)
        self.sell_table3.horizontalHeader().setHighlightSections(False)
        self.sell_table3.verticalHeader().setVisible(False)
        self.sell_table3.verticalHeader().setDefaultSectionSize(20)
        self.sell_table3.verticalHeader().setHighlightSections(False)
        self.verticalLayout_60.addWidget(self.sell_table3, 0, QtCore.Qt.AlignHCenter)
        self.orders3_.addLayout(self.verticalLayout_60)
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.label_87 = QtWidgets.QLabel(self.orders3)
        self.label_87.setObjectName("label_87")
        self.horizontalLayout_73.addWidget(self.label_87, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_59.addLayout(self.horizontalLayout_73)
        self.buy_table3 = QtWidgets.QTableWidget(self.orders3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy_table3.sizePolicy().hasHeightForWidth())
        self.buy_table3.setSizePolicy(sizePolicy)
        self.buy_table3.setMinimumSize(QtCore.QSize(220, 75))
        self.buy_table3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buy_table3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.buy_table3.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.buy_table3.setShowGrid(True)
        self.buy_table3.setGridStyle(QtCore.Qt.SolidLine)
        self.buy_table3.setObjectName("buy_table3")
        self.buy_table3.setColumnCount(0)
        self.buy_table3.setRowCount(0)
        self.buy_table3.horizontalHeader().setVisible(False)
        self.buy_table3.horizontalHeader().setDefaultSectionSize(110)
        self.buy_table3.horizontalHeader().setHighlightSections(False)
        self.buy_table3.verticalHeader().setVisible(False)
        self.buy_table3.verticalHeader().setDefaultSectionSize(20)
        self.buy_table3.verticalHeader().setHighlightSections(False)
        self.verticalLayout_59.addWidget(self.buy_table3, 0, QtCore.Qt.AlignHCenter)
        self.orders3_.addLayout(self.verticalLayout_59)
        self.verticalLayout_55.addWidget(self.orders3)
        self.verticalLayout_54.addLayout(self.verticalLayout_55)
        self.verticalLayout_4.addWidget(self.pair3)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem24)
        self.line = QtWidgets.QFrame(self.pair_group2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem25)
        self.pair4 = QtWidgets.QWidget(self.pair_group2)
        self.pair4.setObjectName("pair4")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.pair4)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_45 = QtWidgets.QLabel(self.pair4)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_39.addWidget(self.label_45)
        self.pair_name4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pair_name4.setFont(font)
        self.pair_name4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pair_name4.setObjectName("pair_name4")
        self.horizontalLayout_39.addWidget(self.pair_name4)
        self.browser_button4 = QtWidgets.QPushButton(self.pair4)
        self.browser_button4.setMaximumSize(QtCore.QSize(20, 20))
        self.browser_button4.setObjectName("browser_button4")
        self.horizontalLayout_39.addWidget(self.browser_button4)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem26)
        self.label_5 = QtWidgets.QLabel(self.pair4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_39.addWidget(self.label_5)
        self.update_time4 = QtWidgets.QLabel(self.pair4)
        self.update_time4.setObjectName("update_time4")
        self.horizontalLayout_39.addWidget(self.update_time4)
        self.allert_symbol4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.allert_symbol4.setFont(font)
        self.allert_symbol4.setObjectName("allert_symbol4")
        self.horizontalLayout_39.addWidget(self.allert_symbol4)
        self.verticalLayout_35.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_46 = QtWidgets.QLabel(self.pair4)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_41.addWidget(self.label_46)
        self.price4 = QtWidgets.QLabel(self.pair4)
        self.price4.setObjectName("price4")
        self.horizontalLayout_41.addWidget(self.price4)
        self.price_converted4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.price_converted4.setFont(font)
        self.price_converted4.setText("")
        self.price_converted4.setObjectName("price_converted4")
        self.horizontalLayout_41.addWidget(self.price_converted4)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem27)
        self.verticalLayout_36.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_48 = QtWidgets.QLabel(self.pair4)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_42.addWidget(self.label_48)
        self.volume4 = QtWidgets.QLabel(self.pair4)
        self.volume4.setObjectName("volume4")
        self.horizontalLayout_42.addWidget(self.volume4)
        self.volume_converted4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volume_converted4.setFont(font)
        self.volume_converted4.setText("")
        self.volume_converted4.setObjectName("volume_converted4")
        self.horizontalLayout_42.addWidget(self.volume_converted4)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem28)
        self.verticalLayout_36.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_40.addLayout(self.verticalLayout_36)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem29)
        self.line_5 = QtWidgets.QFrame(self.pair4)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_40.addWidget(self.line_5)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem30)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_50 = QtWidgets.QLabel(self.pair4)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_43.addWidget(self.label_50)
        self.high4 = QtWidgets.QLabel(self.pair4)
        self.high4.setObjectName("high4")
        self.horizontalLayout_43.addWidget(self.high4)
        self.high_converted4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.high_converted4.setFont(font)
        self.high_converted4.setText("")
        self.high_converted4.setObjectName("high_converted4")
        self.horizontalLayout_43.addWidget(self.high_converted4)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem31)
        self.verticalLayout_37.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_52 = QtWidgets.QLabel(self.pair4)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_44.addWidget(self.label_52)
        self.low4 = QtWidgets.QLabel(self.pair4)
        self.low4.setObjectName("low4")
        self.horizontalLayout_44.addWidget(self.low4)
        self.low_converted4 = QtWidgets.QLabel(self.pair4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.low_converted4.setFont(font)
        self.low_converted4.setText("")
        self.low_converted4.setObjectName("low_converted4")
        self.horizontalLayout_44.addWidget(self.low_converted4)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem32)
        self.verticalLayout_37.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_40.addLayout(self.verticalLayout_37)
        self.verticalLayout_35.addLayout(self.horizontalLayout_40)
        self.verticalLayout_34.addLayout(self.verticalLayout_35)
        self.orders4 = QtWidgets.QWidget(self.pair4)
        self.orders4.setObjectName("orders4")
        self.orders4_ = QtWidgets.QHBoxLayout(self.orders4)
        self.orders4_.setObjectName("orders4_")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_55 = QtWidgets.QLabel(self.orders4)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_47.addWidget(self.label_55, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_39.addLayout(self.horizontalLayout_47)
        self.sell_table4 = QtWidgets.QTableWidget(self.orders4)
        self.sell_table4.setMinimumSize(QtCore.QSize(220, 75))
        self.sell_table4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sell_table4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sell_table4.setShowGrid(True)
        self.sell_table4.setObjectName("sell_table4")
        self.sell_table4.setColumnCount(0)
        self.sell_table4.setRowCount(0)
        self.sell_table4.horizontalHeader().setVisible(False)
        self.sell_table4.horizontalHeader().setDefaultSectionSize(110)
        self.sell_table4.horizontalHeader().setHighlightSections(False)
        self.sell_table4.verticalHeader().setVisible(False)
        self.sell_table4.verticalHeader().setDefaultSectionSize(20)
        self.sell_table4.verticalHeader().setHighlightSections(False)
        self.verticalLayout_39.addWidget(self.sell_table4, 0, QtCore.Qt.AlignHCenter)
        self.orders4_.addLayout(self.verticalLayout_39)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_54 = QtWidgets.QLabel(self.orders4)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_46.addWidget(self.label_54, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_38.addLayout(self.horizontalLayout_46)
        self.buy_table4 = QtWidgets.QTableWidget(self.orders4)
        self.buy_table4.setMinimumSize(QtCore.QSize(220, 75))
        self.buy_table4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buy_table4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.buy_table4.setShowGrid(True)
        self.buy_table4.setObjectName("buy_table4")
        self.buy_table4.setColumnCount(0)
        self.buy_table4.setRowCount(0)
        self.buy_table4.horizontalHeader().setVisible(False)
        self.buy_table4.horizontalHeader().setDefaultSectionSize(110)
        self.buy_table4.horizontalHeader().setHighlightSections(False)
        self.buy_table4.verticalHeader().setVisible(False)
        self.buy_table4.verticalHeader().setDefaultSectionSize(20)
        self.buy_table4.verticalHeader().setHighlightSections(False)
        self.verticalLayout_38.addWidget(self.buy_table4, 0, QtCore.Qt.AlignHCenter)
        self.orders4_.addLayout(self.verticalLayout_38)
        self.verticalLayout_34.addWidget(self.orders4)
        self.verticalLayout_33.addLayout(self.verticalLayout_34)
        self.verticalLayout_4.addWidget(self.pair4)
        self.horizontalLayout_3.addWidget(self.pair_group2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1078, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMune = QtWidgets.QMenu(self.menuBar)
        self.menuMune.setObjectName("menuMune")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAllSettings = QtWidgets.QAction(MainWindow)
        self.actionAllSettings.setObjectName("actionAllSettings")
        self.actionAllerts = QtWidgets.QAction(MainWindow)
        self.actionAllerts.setObjectName("actionAllerts")
        self.actionWindow = QtWidgets.QAction(MainWindow)
        self.actionWindow.setObjectName("actionWindow")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPairs = QtWidgets.QAction(MainWindow)
        self.actionPairs.setObjectName("actionPairs")
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setObjectName("actionReport")
        self.actionLogging = QtWidgets.QAction(MainWindow)
        self.actionLogging.setObjectName("actionLogging")
        self.actionOpen_settings_in_editor = QtWidgets.QAction(MainWindow)
        self.actionOpen_settings_in_editor.setObjectName("actionOpen_settings_in_editor")
        self.actionReload_app = QtWidgets.QAction(MainWindow)
        self.actionReload_app.setObjectName("actionReload_app")
        self.menuMune.addAction(self.actionOpen_settings_in_editor)
        self.menuBar.addAction(self.menuMune.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CryptoChecker"))
        self.update_button.setText(_translate("MainWindow", "Update once"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop autoupdate"))
        self.pushButton_2.setText(_translate("MainWindow", "Pin window"))
        self.label_89.setText(_translate("MainWindow", "Pair:"))
        self.pair_name1.setText(_translate("MainWindow", "---"))
        self.browser_button1.setText(_translate("MainWindow", "E"))
        self.label.setText(_translate("MainWindow", "Updated:"))
        self.update_time1.setText(_translate("MainWindow", "---"))
        self.allert_symbol1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#cc0000;\">!</span></p></body></html>"))
        self.label_90.setText(_translate("MainWindow", "Price:"))
        self.price1.setText(_translate("MainWindow", "---"))
        self.label_92.setText(_translate("MainWindow", "Volume:"))
        self.volume1.setText(_translate("MainWindow", "---"))
        self.label_94.setText(_translate("MainWindow", "High:"))
        self.high1.setText(_translate("MainWindow", "---"))
        self.label_96.setText(_translate("MainWindow", "Low:"))
        self.low1.setText(_translate("MainWindow", "---"))
        self.label_99.setText(_translate("MainWindow", "Sell:"))
        self.label_98.setText(_translate("MainWindow", "Buy:"))
        self.label_67.setText(_translate("MainWindow", "Pair:"))
        self.pair_name2.setText(_translate("MainWindow", "---"))
        self.browser_button2.setText(_translate("MainWindow", "E"))
        self.label_3.setText(_translate("MainWindow", "Updated:"))
        self.update_time2.setText(_translate("MainWindow", "---"))
        self.allert_symbol2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#cc0000;\">!</span></p></body></html>"))
        self.label_68.setText(_translate("MainWindow", "Price:"))
        self.price2.setText(_translate("MainWindow", "---"))
        self.label_70.setText(_translate("MainWindow", "Volume:"))
        self.volume2.setText(_translate("MainWindow", "---"))
        self.label_72.setText(_translate("MainWindow", "High:"))
        self.high2.setText(_translate("MainWindow", "---"))
        self.label_74.setText(_translate("MainWindow", "Low:"))
        self.low2.setText(_translate("MainWindow", "---"))
        self.label_77.setText(_translate("MainWindow", "Sell:"))
        self.label_76.setText(_translate("MainWindow", "Buy:"))
        self.label_78.setText(_translate("MainWindow", "Pair:"))
        self.pair_name3.setText(_translate("MainWindow", "---"))
        self.browser_button3.setText(_translate("MainWindow", "E"))
        self.label_2.setText(_translate("MainWindow", "Updated:"))
        self.update_time3.setText(_translate("MainWindow", "---"))
        self.allert_symbol3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#cc0000;\">!</span></p></body></html>"))
        self.label_79.setText(_translate("MainWindow", "Price:"))
        self.price3.setText(_translate("MainWindow", "---"))
        self.label_81.setText(_translate("MainWindow", "Volume:"))
        self.volume3.setText(_translate("MainWindow", "---"))
        self.label_83.setText(_translate("MainWindow", "High:"))
        self.high3.setText(_translate("MainWindow", "---"))
        self.label_85.setText(_translate("MainWindow", "Low:"))
        self.low3.setText(_translate("MainWindow", "---"))
        self.label_88.setText(_translate("MainWindow", "Sell:"))
        self.label_87.setText(_translate("MainWindow", "Buy:"))
        self.label_45.setText(_translate("MainWindow", "Pair:"))
        self.pair_name4.setText(_translate("MainWindow", "---"))
        self.browser_button4.setText(_translate("MainWindow", "E"))
        self.label_5.setText(_translate("MainWindow", "Updated:"))
        self.update_time4.setText(_translate("MainWindow", "---"))
        self.allert_symbol4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#cc0000;\">!</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "Price:"))
        self.price4.setText(_translate("MainWindow", "---"))
        self.label_48.setText(_translate("MainWindow", "Volume:"))
        self.volume4.setText(_translate("MainWindow", "---"))
        self.label_50.setText(_translate("MainWindow", "High:"))
        self.high4.setText(_translate("MainWindow", "---"))
        self.label_52.setText(_translate("MainWindow", "Low:"))
        self.low4.setText(_translate("MainWindow", "---"))
        self.label_55.setText(_translate("MainWindow", "Sell:"))
        self.label_54.setText(_translate("MainWindow", "Buy:"))
        self.menuMune.setTitle(_translate("MainWindow", "Menu"))
        self.actionAllSettings.setText(_translate("MainWindow", "All settings"))
        self.actionAllerts.setText(_translate("MainWindow", "Allerts"))
        self.actionWindow.setText(_translate("MainWindow", "Window"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionPairs.setText(_translate("MainWindow", "Pairs"))
        self.actionReport.setText(_translate("MainWindow", "Report"))
        self.actionLogging.setText(_translate("MainWindow", "Logging"))
        self.actionOpen_settings_in_editor.setText(_translate("MainWindow", "Open settings in editor"))
        self.actionReload_app.setText(_translate("MainWindow", "Restart app"))


